version: '3.1'
name : vscode-app
services:
  app:
    image: "webdevops/php-apache:7.4"
    #learn more about this image: https://dockerfile.readthedocs.io/en/latest/content/DockerImages/dockerfiles/php-apache.html
    user: 1000:1000
    ports:
      - target: 80
        host_ip: 127.0.0.1
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        host_ip: 127.0.0.1
        published: 443
        protocol: tcp
        mode: host
    expose:
      - "9000"
    volumes:
      - ..\laravel:/app
    environment:
      WEB_DOCUMENT_ROOT: '/app/public'
      PHP_DISMOD: 'amqp,apcu,ctype,ioncube,ldap,mongodb,pcntl,pdo_pgsql,pgsql,tideways,xmlwriter'
      PHP_MEMORY_LIMIT: '512M'
      PHP_DISPLAY_ERRORS: '1'
      PHP_POST_MAX_SIZE: '100M'
      PHP_UPLOAD_MAX_FILESIZE: '100M'
    networks:
      - dev-net
      - internal
  db:
    image: "mariadb:10.4"
    #learn more about this image: https://github.com/docker-library/docs/blob/master/mariadb/README.md
    restart: unless-stopped
    volumes:
      - ..\database:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: laravel@tnm2022
      MARIADB_DATABASE: laravel
      MARIADB_USER: laravel
      MARIADB_PASSWORD: laravel@tnm2022
    expose:
      - "3306"
    networks:
      - internal
  phpmyadmin:
    image: phpmyadmin
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: laravel@tnm2022
      UPLOAD_LIMIT: 200M
    networks:
      - internal
networks:
  dev-net:
    external: true
    name: "dev-net"
  internal:
